### ISSUE TITLE
Single Pass Stereo

### ISSUE THREAD

**Issue by TomGillen** [Placeholder-Software/WetSurfaceDecals#10]
Wet Stuff currently does not work correctly with Unity's single pass stereo. Multipass stereo does work.

Some work has been done towards fixing this, but there are still a few issues that are blocking release.

**Comment by WildStyle69** [comment]
Would love to use this asset in VR, single pass stereo. I've emailed you guys about this, but got no reply. Sorry if this is not the right place.. but if I can help test or troubleshooting, please let me know.

**Comment by martindevans** [comment]
Hi WildStyle. Sorry about missing your email. You've found your way to the right place yourself - We'll post updates about stereoscopic single pass here :)

**Comment by martindevans** [comment]
Wet Stuff does now support single pass stereoscopic rendering as of [Wet Stuff 1.2.0](https://placeholder-software.co.uk/wetstuff/releases/1.2.0.html).

This was actually released a while ago but it looks like we forgot to update this issue, sorry about that for anyone who was waiting.

**Comment by WildStyle69** [comment]
@martindevans -- the Unity asset store page says:

"Wet Stuff requires cameras using `Rendering Path: Deferred`. If you're interested in using Wet Stuff with stereoscopic rendering or the new HDRP pipeline please contact us."

Please can you get the description updated? I've checked back a  few times and didn't realize you now support single-pass which is awesome news.

**Comment by martindevans** [comment]
Sorry about that. As you can tell from only just closing this issue we totally forgot to update things regarding the release of stereoscopic rendering! I've submitted a new description to the asset store, so hopefully that will be fixed soon. Thanks for notifying me 👍
