### ISSUE TITLE
Colored Decals

### ISSUE THREAD

**Issue by TomGillen** [Placeholder-Software/WetSurfaceDecals#11]
It may be possible to support colored decals by adding color information into the wetness saturation texture. We can multiply our diffuse modification factor by this when we apply the wetness effect. This will tint the surface the specified color as it wets.

There would be some limitations; we would only support multiplied blending, and the effect will not properly modify the specular color of the surface. There would also be a small performance hit.

**Comment by martindevans** [comment]
We tried implementing this but it doesn't look particularly good:

![red tint](https://user-images.githubusercontent.com/177519/51641933-9a254a00-1f5f-11e9-9579-fccf4ade387f.png)

Most people who were asking for colour were asking in the context of wanting blood splatters, which this doesn't look like at all!
