### ISSUE TITLE
[Bug] Effects don't render on PS4

### ISSUE THREAD

**Issue by jonNoCode** [Placeholder-Software/WetSurfaceDecals#12]
## Context
Trying out WetStuff on our build and on PC it looks great (really great!) but it does not render on PS4. As soon as the camera with the WetStuff component becomes active, we see an error in the log. 

"RenderingCommandBuffer: invalid pass index 1 in DrawMesh"

Really hoping you can help, even if we're just making local change somewhere in the meantime :)

## Expected Behavior
WetDecals rendering correctly on PS4

## Actual Behavior
Decals do not render (although don't seem to cause any other problems either) and an error is shown in the log.

## Workaround
No workaround available as the effect simply doesn't render.

## Your Environment
Standard Unity Terrain (not CTS) in Unity 2017.4.18f1

- **Wet Decals version used**:    v1.1.0

- **Unity version**: e.g. 2017.4.18f1 LTS

- **Editor Operating System and version**: PS4 & PS4 Pro

- **Build Settings**: PS4 Release and Development Builds

**Comment by martindevans** [comment]
Hi jon,

Is there any extra information associated with that error - e.g. material name or command buffer name? That will help narrow it down a lot.

Try changing the settings in RenderSettings (`Assets/Plugins/PlaceholderSoftware/WetStuff/Resources/RenderSettings`). If disabling one of those fixes the issue that will be a good temporary workaround and will also narrow down the problem a lot.

**Comment by jonNoCode** [comment]
Thanks for the quick reply - much appreciated!

There is no additional info that I can see other than what is mentioned above. I'll dig through the logs and see if I can see anything but it's a bit tricky on PS4. I've disabled one checkbox and will build again and get back to you

**Comment by jonNoCode** [comment]
No luck - but managed to find this in the logs elsewhere (this was with Stencilled turned off):

00:08:23	WARNING: Shader Unsupported: 'Hidden/WetSurfaceModifier' - Pass 'NONSTENCILED' has no vertex shader
00:08:23	WARNING: Shader Unsupported: 'Hidden/WetSurfaceModifier' - Setting to default shader.

**Comment by martindevans** [comment]
That is very odd! The `WetSurfaceModifier` shader code looks like this:

```
Pass
{
    Name "NonStenciled"

    CGPROGRAM
    #pragma vertex vert
    #pragma fragment frag
    #pragma exclude_renderers nomrt

    #include "UnityCG.cginc"
    #include "WetSurfaceModifier.cginc"
    ENDCG
}
```

As you can see, this defines the vertex shader as `vert` and imports `WetSurfaceModifier.cginc`, which in turns contains this code:

```
struct appdata
{
    float4 vertex : POSITION;
    float2 uv : TEXCOORD0;
};

struct v2f
{
    float2 uv : TEXCOORD0;
    float4 vertex : SV_POSITION;
};

v2f vert(appdata v)
{
    v2f o;
    o.vertex = float4(v.vertex.xyz, 1);
    o.uv = v.uv;
    return o;
}
```

So there's definitely a vertex shader defined here.

Unfortunately I don't think we can access the PS4 documentation, are you aware of any restrictions on vertex shaders on the console which may cause this shader to not work (e.g. registers we're using which don't exist on PS4)? It may be worth opening up a support thread on the internal PS4 developer forums mentioning this issue, just in case there's something like that they can spot.

**Comment by TomGillen** [comment]
Sometimes shader errors are not reported in the editor console. Are there any shader compile errors shown in the inspector for the shader file itself (`/Assets/Plugins/PlaceholderSoftware/WetStuff/Resources/WetSurfaceModifier.shader`)?
