### ISSUE TITLE
[bug]Enviro Compatibility

### ISSUE THREAD

**Issue by spinalcord** [Placeholder-Software/WetSurfaceDecals#14]
## Context
Null refrences with Wet Stuff For Enviro.

## Workaround
you can query some null refrences, but there are also incorrect material nameIDs that leads to null reference.

## Steps to Reproduce
After Importing Enviro.

## Your Environment
Unity version 2019, Windows 10
WetStuff Version 2.0.1
Wet Stuff For Enviro 2.0.0
Envrio 2.1.1

**Comment by martindevans** [comment]
Thanks for reporting this - it looks like there's been an update to Enviro that's broken some of the references from the integration into Enviro. We'll sort it out as soon as possible :)

**Comment by spinalcord** [comment]
You are fast. It seams it was, and is a enviro issue. I have mistaken the Enviro script with Wet Stuff For Enviro script. It seems that Enviro is not fully compatible with unity 2019, so no worries :P

**Comment by martindevans** [comment]
Aha, good to know it's an Enviro+2019 issue thanks for that :)
