### ISSUE TITLE
Small Feedback & Vegetation Studio +Mesh trees

### ISSUE THREAD

**Issue by Necka44** [Placeholder-Software/WetSurfaceDecals#2]
Hi guys,

Starting to test Wet surface decals, this isn't necessary a bug, but more a feedback - if you wish to have the feedbacks via mails or your Reddit, please tell me

The asset is quite solid so far with just testing the Surface decal (not the drops and so on, will come later as I will try to have enviro rain to paint the surface globally)

First I didn't know what to expect as I want to have my whole terrain covered when rain drops, so I've just created an empty, attached the decal and made it the size of my small test terrain (512x512)

Performances wise, I didn't see a difference, maybe 3 to 5 FPS top, that's really good

I've used the Tri-Planar setting to get my cliffs wet as well, even though so far I'm not sure to understand properly how to use the masks on each axis and each channels (RGBA). I'm not super good with the technical part of masks and textures, I might dig in this and check your documentation in details

My results need some tuning but it works quite well

![image](https://user-images.githubusercontent.com/39954105/41481584-de7b46b4-70d2-11e8-884e-d3c1efe936d8.png)

I have Vegetation studio with Instanced indirect rendering (but this part doesn't necessarily matters) objects/large objects thrown into VS will get wet, but the rendering on mesh trees isn't good, it just darkened the trees and that's all. I don't know if Trees could be in the scope of your asset, I think it could be a great thing that the effects works on those too and I can test things if you need

I'll move on working on the integration with Enviro Rain and try some splashes as well 

thanks for this future great asset

**Comment by TomGillen** [comment]
Sorry about the delay getting back to you. Can you provide examples of what the trees look like with and without wet stuff, and are they using the standard shader or a custom one?

**Comment by Necka44** [comment]
Ah, sorry I missed this reply
I will try to rebuild a little scene this week and give you some feedback with screenshots and shader details

The Shader are custom ones (Fantasy Adventure Environment on the Asset store)
