### ISSUE TITLE
Documentation website - header / footer overlap the content

### ISSUE THREAD

**Issue by gekidoslair** [Placeholder-Software/WetSurfaceDecals#20]
This is a bit of a side note I guess, but the docs website has some issues - the header covers up / hides the content on all of the pages. 

<img width="883" alt="2020-06-24 23_27_15-WetDecal - Wet Stuff" src="https://user-images.githubusercontent.com/4552687/85667285-46e28a00-b672-11ea-9047-eca92854fe8f.png">

**Comment by martindevans** [comment]
Thanks for reporting this.

I'm not sure if it's possible for me to fix it unfortunately because we're using a prebuilt HTML template for the docs. I'll investigate it soon :)

**Comment by martindevans** [comment]
Fixed! Thanks for reporting this.
