### ISSUE TITLE
[Bug] 4. Particles (Splat) example doesn't do anything

### ISSUE THREAD

**Issue by forsini** [Placeholder-Software/WetSurfaceDecals#25]
## Context
Running the 4. Particles (Splat) demo doesn't show any particles or / and effects

## Expected Behavior
You tell me :) the scene doesn't change

## Actual Behavior
Nothing happens - no Wetness

## Workaround
Tried to debug the particle system quick but still haven't found the issue

## Fix
NA
## Steps to Reproduce
Run the 4. Particles (Splat) demo inside the Editor

## Your Environment
Windows 10 - Unity 2019.3.15

- **Wet Decals version used**:  v2.0.3

- **Unity version**:  2019.3.15

- **Editor Operating System and version**:  Microsoft Windows 10 Pro 10.0.10586 (x64)

- **Build Settings**: Android / Vulkan / OpenGLES2/3 but it is running in the Unity Editor for now

- **Link to your project**: NA

**Comment by martindevans** [comment]
Thanks for reporting this. It looks like the particle emitter has managed to reset the probability of emitting to zero for that scene (presumably as part of the upgrade process).

<img width="456" alt="Unity_2020-06-30_21-48-38" src="https://user-images.githubusercontent.com/177519/86175565-79313300-bb1b-11ea-8c69-882d08f60c3a.png">

Change the probability value on the `Particle System` GameObject (as shown above) to `1.0`

I'll add this fix to the next release of Wet Stuff.

**Comment by forsini** [comment]
Thank you, Martin - forgot to check Emission! All good now

**Comment by martindevans** [comment]
This fix has now been released on the asset store with [Wet Stuff 4.1.0](https://placeholder-software.co.uk/wetstuff/releases/4.1.0.html). Thanks for reporting it.
