### ISSUE TITLE
GC every frame

### ISSUE THREAD

**Issue by fender** [Placeholder-Software/WetSurfaceDecals#28]
## Context
There is a little GC being created every frame.

![](https://cdn.discordapp.com/attachments/631607446330277919/791411549162962994/unknown.png)

## Expected Behavior
There should be 0B of GC allocated.

## Actual Behavior
There is about 150B of GC. Not a huge amount but more than a game should have each frame.

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. I think you just need to turn WetStuff on.
2. Profile

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Wet Decals version used**: 4.1.0

- **Unity version**: 2019.4.13f1

- **Editor Operating System and version**: Windows 10

**Comment by martindevans** [comment]
I've tracked this down to an allocation of an array in `Assets/Plugins/PlaceholderSoftware/WetStuff/Core/WetAttributeModifier.cs` (line 108). We'll be releasing a new version of Wet Stuff soon that fixes it (by preallocating the array in a static field).

**Comment by fender** [comment]
@martindevans Perfect, thanks. Would you be a able to ping me here or in Discord once that goes live? Hoping to get it included in our final release build before launch Jan 28th. 🙏

**Comment by martindevans** [comment]
I'll comment on this issue and close it once it's live. You should get an email notification about that if you've subscribed to this issue :)

**Comment by martindevans** [comment]
[Wet Stuff 4.1.2](https://placeholder-software.co.uk/wetstuff/releases/4.1.2.html) has just been approved by Unity and is now live on the asset store. That include the fix for this :)

**Comment by fender** [comment]
Nice one Martin. 👍
