### ISSUE TITLE
Navigation between Timeline clips could be improved

### ISSUE THREAD

**Issue by Necka44** [Placeholder-Software/WetSurfaceDecals#3]
Hi,

When configuring the Timeline "Decal settings" clips I found myself having to always unfold the Saturation, X, Y, Z layers while going back and forth between multiple clips. It's working for sure, but it's quite time consuming.

Here are the settings I'm speaking about; the headers that can fold/unfold: 
![image](https://user-images.githubusercontent.com/39954105/41495036-9e0ca7f2-711e-11e8-88af-976a08f3112b.png)

If the last fold/unfold setting could be saved so we jump from clip "dry" to clip "wet" and be able to compare the settings in the blink of an eye, that would be great.

Or maybe having them unfold by default.

This point is also valid in the component configuration itself. I know we got a lot of stuff there, but the issue is just that they refold automatically. If they could just "save" the last unfold state, that would be awesome

No idea how complicated it would be for you to improve, but that would be less hassle to configure the whole system

In my experience so far, I was playing only with layer Y and Z. Having those two layers opened while jumping from the component (or Timeline clip) to another and back to the component would be useful

Thanks!

Edit: Actually the Wet saturation is unfold by default, which is good

**Comment by Necka44** [comment]
Literally 1 minute after I posted this, you guys released the latest beta that fix this issue

> •	Decal inspector editor sections now remember if they were opened or closed.

So, thank you I guess :)

Keep it up

**Comment by TomGillen** [comment]
We have only fixed it in the insepctor for the decals themselves, but not the inspector for the timeline clip. I'll leave this issue open until both have been resolved.

**Comment by martindevans** [comment]
Timeline clips do also remember their state, I added that in at the same time as the decal inspector remembering the state :)
