### ISSUE TITLE
tutorial for Gaia + enviro + wet stuff

### ISSUE THREAD

**Issue by TomMann** [Placeholder-Software/WetSurfaceDecals#30]
Hey,
pretty new to unity, trying to link this together with as the title says Gaia 2021, enviro and this component however I've not managed so far to get the wetsurface to work on the terrain created.  The documentation seems to be a little light and there is not very many videos on youtube either.  

My current state is that I have Gaia terrain with enviro sky manager for gaia, I have the wetstuff script on my camera I have tried a number of things going off videos such as assigning the auto puddle to the terrain but all to no avail.  I'm guessing I've missed some important step but as of yet its not that clear to me how to use your script, any assistance would be great.

**Comment by martindevans** [comment]
Do the demo scenes included in the integration package (`https://github.com/TomGillen/WetSurfaceDecals/tree/master/Assets/PlaceholderSoftware/WetStuff/Integrations/Enviro/Demo`) work as expected - if so, that confirms that everything is installed properly in your project.

If the demo works the best documentation for how to set up your scene correctly is the readme included in the package: `Assets/PlaceholderSoftware/WetStuff/Integrations/Enviro/Readme.txt`.

If you've followed those steps and you're still not seeing anything, check [these docs](https://wetsurfacedecals.readthedocs.io/en/latest/GettingStarted/Compatibility/) which allows you to check that the specific item you're trying to modify is compatible with Wet Stuff.

**Comment by TomMann** [comment]
Thanks this helped, I now have a puddle.  Is there anyway to apply this to global terrain rather than having to manually apply the decal where I want this effect ?

**Comment by martindevans** [comment]
You can't apply the Wet Stuff effect to a single item (e.g. "the entire terrain") - instead it has to be done through the decals (this is just the nature of how it works through modifying the renderer internals). You could make a single massive decal which covers the entire terrain. However, that runs the risk of making other things in the scene which move through the decal wet as well, so it's generally better to make smaller puddles in precise positions.
