### ISSUE TITLE
I have Enviro Installed. But WetSurface give errors after importing

### ISSUE THREAD

**Issue by Talha00Abbas** [Placeholder-Software/WetSurfaceDecals#31]
WetSurface Decals give errors after importing. I have the latest Enviro version installed. I also tried it with old versions it doesn't work and give errors in the console. Please help

**Comment by martindevans** [comment]
What errors do you get?

**Comment by Talha00Abbas** [comment]
![DD](https://user-images.githubusercontent.com/88454435/128232878-a6987ae9-96e5-45a0-98d2-9aa1489142c5.PNG)
Here are the errors

**Comment by Talha00Abbas** [comment]
It should works with enviro and I have purchased the Enviro Full package from unity asset store

**Comment by martindevans** [comment]
Some of the paths in the errors are totally wrong - it looks like you've installed Wet Stuff into the wrong location!

For example, you should have: `Assets/Plugins/PlaceholderSoftware/WetStuff/WetDecal.cs`, but errors 2 shows it at a very different path!

Could you delete all of the Wet Stuff related package and re-install them completely (after restarting the editor). Install [Wet Stuff](https://assetstore.unity.com/packages/tools/particles-effects/wet-stuff-118969) and verify that it's in the correct location before installing [the integration package](https://assetstore.unity.com/packages/tools/particles-effects/wet-stuff-for-enviro-133615).

**Comment by Talha00Abbas** [comment]
I will have to purchase both Wet Stuff and Wet Stuff Enviro Integration. Right??

**Comment by martindevans** [comment]
`Wet Stuff For Enviro` is a free extension to the paid `Wet Stuff` package :)

**Comment by Talha00Abbas** [comment]
So I have to purchase Wet Stuff. Right

If that's right then I've done it wrong. Thanks for your help

I'm gonna buy Wet Stuff Right now

**Comment by martindevans** [comment]
I'll close this for now, but don't hesitate to open another issue if you still have a problem after installing Wet Stuff.
