### ISSUE TITLE
The asset does not work in vr.

### ISSUE THREAD

**Issue by frtstudio** [Placeholder-Software/WetSurfaceDecals#32]
## Expected Behavior

Assets not working properly in vr.

see image below
The effect seems to be reversed.
And as the camera moves, the effect moves.

![샘플1](https://user-images.githubusercontent.com/92841979/138031843-d71cda52-a479-4887-a38d-0665d8f4aaf2.png)

I bought it knowing it was an asset that could be used in vr.
I'd love to know the solution.

The Unity version I am using is 201901.2f1.
The vr device is vive pro.

**Comment by TomGillen** [comment]
I can't reproduce this with an Oculus headset, and we don't have a Vive Pro available to test. However, this looks exactly like the UV coordinates are incorrectly flipped in the gbuffer modification shader.

Can you try finding lines 23-26 in `/Assets/Plugins/PlaceholderSoftware/WetStuff/Resources/WetSurfaceModifier.cginc`:

```
#if !UNITY_UV_STARTS_AT_TOP
    if (_GBufferSpecularCopy_TexelSize.y > 0)
        v.uv.y = 1 - v.uv.y;
#endif
```

And try both commenting out those lines entirely (to ensure the flip can't happen), and replacing this block with `v.uv.y = 1 - v.uv.y` (to force the flip to always happen), and see what happens in each case?

I suspect that one of these two will fix your issue, but in doing so will break rendering on some platforms.

**Comment by frtstudio** [comment]
![image](https://user-images.githubusercontent.com/92841979/138191662-24fc0f7c-3315-42d4-bdaf-336b094b1be5.png)
look at the image

I commented out as you said but it doesn't solve the problem.

**Comment by martindevans** [comment]
Could you also try replacing that block with `v.uv.y = 1 - v.uv.y` please, thanks.
