### ISSUE TITLE
"RenderingCommandBuffer: invalid pass index 3 in DrawMesh" error with Beta3 and Dry demo scene

### ISSUE THREAD

**Issue by Necka44** [Placeholder-Software/WetSurfaceDecals#5]
Hi,

I've updated to Beta 3 and since that I've got this non removable error in the console (which doesn't block Play mode though) when opening the Demo 7.
![image](https://user-images.githubusercontent.com/39954105/41499278-b40002e8-717d-11e8-8c73-695ced2d2d00.png)

The Demo scene doesn't seem to work at all because of this (no dry effect. Try to play with the sliders around but nothing)

**Comment by TomGillen** [comment]
Well that is certainly interesting. What version of Unity are you using, and are there any compile errors for the shaders (`Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/Resources/WetSurfaceMask.shader` and `DrySurfaceMask.shader` in the same folder)? Unity does not always list shader compile errors in the console, so you will need to find the asset and see if it lists and errors in the inspector.

**Comment by Necka44** [comment]
Ah.. I'll look stupid now. But as explained in my other report, I usually rename Resources folders to avoid long wait for Playmode/Build and bigger build size.

I do still have errors but the Demo scene works 

![image](https://user-images.githubusercontent.com/39954105/41503323-d5033174-71d0-11e8-98d9-a4fbbc904f4e.png)

Are those Shader path hard-coded somewhere?

**Comment by TomGillen** [comment]
It is using a relative file path, expecting the .cginc to be next to the .shader files.

**Comment by Necka44** [comment]
It's there, opened the Demo Rain and got no wetness, errors in the console, folders are also named by default
![image](https://user-images.githubusercontent.com/39954105/41504260-b547bcd8-71e9-11e8-863c-f402bedf1f30.png)

Weird part is that I was working on my own scene (wetness working fine, no errors) and switched to the demo scene to check how you deal with puddles. So it was just a scene switch that threw those errors, but I'm not sure if it's just that

**Comment by Necka44** [comment]
Sorry, forgot to add from the beginning: Unity 2017.4.5

Also went back to my own scene, and no wetness working

Restarting Unity: it's working. Going to any demo, double click on puddle to zoom in, errors in the consoles 

In all cases, the shaders have the errors that they can't open the Core.cginc

![image](https://user-images.githubusercontent.com/39954105/41504283-8df35f24-71ea-11e8-9bdb-0e43502ae1e9.png)
![image](https://user-images.githubusercontent.com/39954105/41504286-9a612714-71ea-11e8-9adf-c3ef69f45cdd.png)

![image](https://user-images.githubusercontent.com/39954105/41504287-a206b9fc-71ea-11e8-85ec-9777756a67ff.png)
