### ISSUE TITLE
Timeline FormatException: Index (zero based)

### ISSUE THREAD

**Issue by Necka44** [Placeholder-Software/WetSurfaceDecals#6]
While playing around with Timeline, I noticed a console error at each modification of the track (adding a track, a clip, modifying the values and the worst when you got the error at each frame: when playing the timeline itself)

Errors happen in editor mode as well in playmode
It seems that the Rain demo breaks because of that (only the puddles come wet)

![image](https://user-images.githubusercontent.com/39954105/41511378-0df9d38e-7276-11e8-92cb-f41b9b950c14.png)

`FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <cfc149f8218b496788d8493c87de777a>:0)
System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <cfc149f8218b496788d8493c87de777a>:0)
System.String.Format (System.String format, System.Object arg0) (at <cfc149f8218b496788d8493c87de777a>:0)
PlaceholderSoftware.WetSurfaceDecals.Debugging.Log.UserErrorMessage (System.String problem, System.String likelyCause, System.String documentationLink, System.String guid) (at Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/Core/Debugging/Log.cs:436)
PlaceholderSoftware.WetSurfaceDecals.DecalLayerChannel.set_InputRangeSoftness (System.Single value) (at Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/Core/IDecalSettings.cs:347)
PlaceholderSoftware.WetSurfaceDecals.DecalLayerChannel.Apply (PlaceholderSoftware.WetSurfaceDecals.Timeline.Settings.DecalSettingsDataContainer+DecalLayerChannelData data) (at Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/Core/IDecalSettings.cs:444)
PlaceholderSoftware.WetSurfaceDecals.DecalLayer.Apply (PlaceholderSoftware.WetSurfaceDecals.Timeline.Settings.DecalSettingsDataContainer+DecalLayerData data) (at Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/Core/IDecalSettings.cs:247)
PlaceholderSoftware.WetSurfaceDecals.DecalSettings.Apply (PlaceholderSoftware.WetSurfaceDecals.Timeline.Settings.DecalSettingsDataContainer+DecalSettingsData data) (at Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/WetDecal.cs:215)
PlaceholderSoftware.WetSurfaceDecals.Timeline.Settings.DecalSettingsMixer.ApplyState (PlaceholderSoftware.WetSurfaceDecals.Timeline.Settings.DecalSettingsDataContainer+DecalSettingsData intermediate, PlaceholderSoftware.WetSurfaceDecals.WetDecal trackBinding) (at Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/Core/Timeline/Settings/DecalSettingsMixer.cs:21)
PlaceholderSoftware.WetSurfaceDecals.Timeline.TemplatedTimeline`6+BaseMixer[TData,TClip,TMixer,TTrack,TIntermediate,TBinding].ProcessFrame (UnityEngine.Playables.Playable playable, UnityEngine.Playables.FrameData info, System.Object playerData) (at Assets/Plugins/PlaceholderSoftware/WetSurfaceDecals/Core/Timeline/TimelineTemplate.cs:113)
`

**Comment by martindevans** [comment]
I noticed this myself earlier today, a fix is waiting to be merged :)
