### ISSUE TITLE
Asset Store Links are inconsistent

### ISSUE THREAD

**Issue by hariedo** [Placeholder-Software/WetSurfaceDecals#9]
## Context

The various links in the Asset Store are inconsistent and need updating.

Inside the dark blue banner there are good links for:

* Documentation - https://wetsurfacedecals.readthedocs.io/en/latest/
* Discussion Forum - https://www.reddit.com/r/WetStuff/
* Website - https://placeholder-software.co.uk/wetstuff/
* Issue Tracker - GitHub, here

Below the preview images there are inconsistent links for:

* Support E-mail - perhaps correct admin@placeholder-software.co.uk
* Support Website - https://placeholder-software.co.uk/dissonance/
* Publisher's Website - https://placeholder-software.co.uk/dissonance/

Maybe you need a landing page for the publisher links, to let folks choose across products.

**Comment by martindevans** [comment]
The support website and the publishers website both are links to `https://placeholder-software.co.uk/` which just redirects to the dissonance page, that was fine when we only published Dissonance but now it's not. As you say I'll need to build a landing page which links out to the various other assets.

Thanks for the detailed report :)
